#Filim Booking Application
trigger:
- Master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Junit Stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Running Spring demo app unit test'
          - task: Maven@3
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'Test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              pmdRunAnalysis: true
              findBugsRunAnalysis: true